# TODO: stuff to add / fix 
# [ ] Unit Tests

"""
SERVER:
-------------------------------------------------
# Room keys:
Should maybe be generated by hash(username, datetime) 
if that makes sense, otherwise do it a different way
should not be deleted when emptied
instead maybe routinely delete unused room data?
-------------------------------------------------
# Robust Reconnections
I have no idea how this will turn out
-------------------------------------------------
# Username should be give on connection
-------------------------------------------------
"""

import socketio
from flask import Flask, g, request
from app.routes import routes 
from app.events import Namespace

flask_app = Flask(__name__)
flask_app.register_blueprint(routes)
sio = socketio.Server(cors_allowed_origins="http://localhost:3000")
sio.register_namespace(Namespace("/test"))
app = socketio.WSGIApp(sio, flask_app)

# TODO: is this working??
@flask_app.teardown_appcontext
def close_connection(exception):
  db = getattr(g, '_database', None)
  if db is not None:
    db.close()
